UPLOAD_FOLDER = './static/uploaded/'

ADM_USERNAME = "admin"
ADM_PASS_SHA256 = "FOOBAR2ccd6FOOBARdc1FOOBAR3f4c074d77FOOBAR"

# for console.py
CONSUMER_KEY = 'FOOBARo323pyKFOOBAREXUR'
CONSUMER_SECRET = 'FOOBARuPptaWRDqGFOOBARjcOMloUpWoxFwKYZ4V'
ACCESS_TOKEN = 'FOOBAR84098859011-elFOOBARcraJOEH8knurrB'
ACCESS_TOKEN_SECRET = 'FOOBARXr79e2xK0apFOOBAR8YrFCAeDV6a'

REDUCE_UPLOADED_IMAGE_WIDTH = 950
ADDITIONAL_QUERY_SUFFIX = "-(from:SOME_ACCOUNT_NAME OR from:SOME_ACCOUNT_NAME2)"

FLASK_SECRET_KEY = b'FOOBAR"2+_23+FOOBAR\n\xec]/'

DB_SERVER = 'localhost'
DB_PORT = 27017
DB_NAME = 'botski_db'

HOW_MANY_TWEETS_TO_FIND = 800
